import './globals.css'
import { Secular_One } from 'next/font/google'

const secularFont = Secular_One({
  subsets: ['latin'],
  weight: '400',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${secularFont.className}`}>{children}</body>
    </html>
  )
}
